=== pedro00dk/ptray/schema/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "JSON Schema for Plugable Tray (ptray) specification files",
    "type": "object",
    "properties": {
        "name": {
            "description": "The name of the specification",
            "type": "string",
            "minLength": 2,
            "maxLength": 10
        },
        "interval": {
            "description": "The interval in seconds of the execution",
            "type": "number",
            "minimum": 1,
            "maximum": 600,
            "default": 5
        },
        "command": {
            "description": "The command to run, if the result error code is not zero, the specification fails",
            "type": "array",
            "items": {
                "description": "Every array element is one part of th command separated by space and without quotes",
                "type": "string"
            },
            "minItems": 1
        },
        "filter": {
            "description": "The strategy to filter the result provided by the command, the output of this step is a dictionary of integer->string",
            "type": "object",
            "properties": {
                "all": {
                    "description": "The result will be used entirely as as single string by the next steps, outputs {0: entire_command_output}",
                    "type": "null"
                },
                "lines": {
                    "description": "Only the received lines indices will be extracted from the result, outputs {line: command_output_line}, missing lines are ignored",
                    "type": "array",
                    "items": {
                        "description": "The line index to select",
                        "type": "number"
                    },
                    "minItems": 1
                },
                "match": {
                    "description": "Search for a pattern (https://docs.python.org/3/library/re.html) in the result, groups are ignored, outputs {match_order:match_string}",
                    "type": "string"
                }
            },
            "minProperties": 1,
            "maxProperties": 1
        },
        "extract": {
            "description": "An array of rules to extract helpful information from the filtered dicts using patterns",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "key": {
                        "description": "The index selector, can be an array of indices or a range, if some rules are overlapping indices, the latter is persisted",
                        "oneOf": [
                            {
                                "type": "array",
                                "items": {
                                    "description": "Index to select",
                                    "type": "number"
                                }
                            },
                            {
                                "type": "object",
                                "properties": {
                                    "from": {
                                        "description": "Start range index, inclusive",
                                        "type": "number"
                                    },
                                    "to": {
                                        "description": "End range index, inclusive",
                                        "type": "number"
                                    }
                                },
                                "minProperties": 2,
                                "maxProperties": 2
                            }
                        ]
                    },
                    "data": {
                        "description": "The data extractor, a string pattern with groups (groups are indexed together in the result, being accessible by name or order), the entire match is always available at group 0, mismatches return null to the next step",
                        "type": "string",
                        "default": ".*",
                        "minLength": 1
                    }
                },
                "minProperties": 2,
                "maxProperties": 2
            },
            "minItems": 1
        }
    },
    "required": [
        "name",
        "interval",
        "command",
        "filter",
        "extract"
    ]
}

=== pedro00dk/ptray/specs/disk.json
{
    "$schema": "https://raw.githubusercontent.com/pedro00dk/ptray/master/schema/schema.json",
    "name": "disk",
    "interval": 30,
    "command": [
        "df",
        "-BM"
    ],
    "filter": {
        "match": "(?imux) ^ /dev/sd[^\\s]+ .+ $"
    },
    "extract": [
        {
            "key": {
                "from": 0,
                "to": 1000
            },
            "data": "(?imux) ^ (?P<drive>[^\\s]+) \\s+ (\\d+) M \\s+ (\\d+) M \\s+ (\\d+) M \\s+ (?P<used>\\d+) % (?P<mount>.*) $"
        }
    ]
}
